export const FETCH_BLOG_POST_REEQUEST = "FETCH_BLOG_POST_REEQUEST";
export const FETCH_BLOG_POST_SUCCESS = "FETCH_BLOG_POST_SUCCESS";
export const FETCH_BLOG_POST_FAULIURE = "FETCH_BLOG_POST_FAULIURE";


export const FETCH_SINGLE_BLOG_POST_REEQUEST = "FETCH_SINGLE_BLOG_POST_REEQUEST";
export const FETCH_SINGLE_BLOG_POST_SUCCESS = "FETCH_SINGLE_BLOG_POST_SUCCESS";
export const FETCH_SINGLE_BLOG_POST_FAULIURE = "FETCH_SINGLE_BLOG_POST_FAULIURE";


export const CREATE_BLOG_POST_REEQUEST = "CREATE_BLOG_POST_REEQUEST";
export const CREATE_BLOG_POST_SUCCESS = "CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAULIURE = "CREATE_BLOG_POST_FAULIURE";


export const UPDATE_BLOG_POST_REEQUEST = "UPDATE_BLOG_POST_REEQUEST";
export const UPDATE_BLOG_POST_SUCCESS = "UPDATE_BLOG_POST_SUCCESS";
export const UPDATE_BLOG_POST_FAULIURE = "UPDATE_BLOG_POST_FAULIURE";